server:
     port: 8083     
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: Nunarijal12# 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: REVIEW
    
  config:
    import: optional:configserver:http://localhost:8085
   
   
   
okta:
  oauth2:
    issuer: https://dev-26107400.okta.com/oauth2/default
    audience: api://default 
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
  